apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-cluster-apps
  namespace: argocd

spec:
  generators:
    - list:
        elements:
          - appName: modern-chair
            repoURL: https://github.com/Honeyshah624/MordenChair.git
            chartPath: modern-chair-chart
            namespace: modern-chair
            valuesFile: clusters/local-minikube/modern-chair-values.yaml

          - appName: weather-app
            repoURL: https://github.com/Honeyshah624/Weather-app.git
            chartPath: weather-app-chart
            namespace: weather-app
            valuesFile: clusters/local-minikube/weather-app-values.yaml

          - appName: tic-tac-toe
            repoURL: https://github.com/Honeyshah624/Tic-tac-toe.git
            chartPath: tic-tac-toe-chart
            namespace: tic-tac-toe
            valuesFile: clusters/local-minikube/tic-tac-toe-values.yaml

  template:
    metadata:
      name: "{{appName}}"

    spec:
      project: default

      sources:
        - repoURL: "{{repoURL}}"
          targetRevision: HEAD
          path: "{{chartPath}}"
          helm:
            releaseName: "{{appName}}"
            valueFiles:
              - $values/{{valuesFile}}

        - repoURL: https://github.com/Honeyshah624/GitOps-argocd.git
          targetRevision: HEAD
          ref: values

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true