apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: practice-multi-cluster-apps
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  deploy: "true"

          - git:
              repoURL: https://github.com/Honeyshah624/GitOps-argocd.git
              revision: HEAD
              directories:
                - path: charts/*

  template:
    metadata:
      name: "{{.metadata.labels.env}}-{{.path.basename}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/Honeyshah624/GitOps-argocd.git
        targetRevision: HEAD
        path: "{{.path.path}}"
        helm:
          releaseName: "{{.metadata.labels.env}}-{{.path.basename}}"
          valueFiles:
            - values.yaml
            - values/{{.name}}.yml

      destination:
        name: "{{.name}}"
        namespace: "{{.metadata.labels.env}}-{{.path.basename}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true